

/// FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';


// FIREBASE NODE ACTIONS
export const GET_FIREBASE_NODE = 'GET_FIREBASE_NODE';
export const CREATE_FIREBASE_NODE = 'CREATE_FIREBASE_NODE';
export const SET_FIREBASE_NODE = 'SET_FIREBASE_NODE';

// CLIENT NODE ACTIONS
export const SET_CLIENT_NODE = 'SET_CLIENT_NODE';
